**Scalars** - contain single value that is a numpy datatype- 0 dimensional in nature

In [3]:
import numpy as np
print(np.isscalar(3.14))
print(np.isscalar(np.array(3.14)))

1
1
False
False
True
False


**Vectors** - 1D array or a 2D array with a single row or column
Possible operations - vector addition, subtraction, multiplication, scalar operations, dot product and cross product

In [7]:
import numpy as np
vec_row = np.array([[1,2,3]])
vec_column = np.array([[1],[2],[3],[4]])
x = np.array([10,11,12])
y = np.array([1,2,3])

#Shape and dimension
print(vec_row.shape, vec_row.ndim)
print(vec_column.shape, vec_row.ndim)
print(x.shape, x.ndim)

#Vector operations
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(np.dot(x,y))
print(x@y)

#vectorised addition
print(vec_row+x)

(1, 3) 2
(4, 1) 2
(3,) 1
[11 13 15]
[9 9 9]
[10 22 36]
[10.   5.5  4. ]
68
68
[[11 13 15]]


**Vector broadcasting**- applyling arithmetic operations on arrays of different shapes, stretches the smaller array across the larger one till their shapes match

Condition- either no. of columns of first array = no. of rows of second array

or atleast a row or column in either array is exactly 1

In [10]:
import numpy as np
x = np.array([[1,2,3]]) # (1,3)
y = np.array([[1],[2],[3]]) #(3,1)
print(x+y)

a = np.array([[12,13,14]])
b = np.array([1,2])
print(a+b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


ValueError: operands could not be broadcast together with shapes (1,3) (2,) 

**Matrices:**  2D array consisting of rows and columns

In [14]:
import numpy as np
x = np.array([[1,2]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.ndim, x.shape, x.size)
print(y.ndim, y.shape, y.size)

2 (1, 2) 2
2 (3, 3) 9


**Matrix multiplication:** every row of first array is multiplied with corresponding column of second array- hence no. of rows in first array = no. of columns in second array

In [15]:
import numpy as np
x= np.array([[1,2],[3,4],[5,6]])
y = np.array([[1,2,3,4],[4,5,6,7]])
print(x@y)
print(np.matmul(x,y))

[[ 9 12 15 18]
 [19 26 33 40]
 [29 40 51 62]]
[[ 9 12 15 18]
 [19 26 33 40]
 [29 40 51 62]]


**Transpose of a matrix:** All the rows are converted to corresponding columns

In [17]:
import numpy as np
x = np.array([[[1,2],[2,3],[3,4]]])
print(x.shape)
print(x.T)
print(x.T.shape)

(1, 3, 2)
[[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]]
(2, 3, 1)


**Tensors:** multidimensional arrays that store input data and parameters like weights and biases in neural networks

Advantages  
@can run on GPU for hardware acceleration

 @take care of backpropagation with automatic differentiation


In [18]:
import torch
import numpy as np
data = [[1,2],[3,4],[5,6]]
x_data = torch.tensor(data)
x = np.array(data)
x_np = torch.from_numpy(x)
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(x_data, x_data.shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[1, 2],
        [3, 4],
        [5, 6]]) torch.Size([3, 2])
tensor([[0.9157, 0.8436, 0.8615],
        [0.4156, 0.6965, 0.5502]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
import torch
a = torch.tensor([[1., 2.],
                  [3., 4.]])

b = torch.tensor([[5., 6.],
                  [7., 8.]])

print(a + b)
print(a - b)
print(a * b)       # element-wise
print(a / b)       # element-wise

print(a@b)

tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[19., 22.],
        [43., 50.]])


In [22]:
import torch
a = torch.randn(2, 3)
b = torch.randn(3, 4)

print(a @ b)
print((a @ b).shape)

c = torch.randn(2, 5)

a @ c


tensor([[-1.1682, -0.0540, -0.5815, -1.5986],
        [ 0.0949,  0.1538,  1.0593,  1.3293]])
torch.Size([2, 4])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x5)

In [25]:
import torch
x = torch.tensor([1, 2, 3, 4, 5, 6])

print(x.shape)

x = x.reshape(2, 3)
print(x)
print(x.shape)

print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

y = x.unsqueeze(0)
print(y.shape)

print(y.squeeze().shape)


torch.Size([6])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([1, 2, 3])
torch.Size([2, 3])


In [27]:
import torch
x = torch.tensor([
    [1., 2., 3.],
    [4., 5., 6.]
])

b = torch.tensor([10., 20., 30.])

print(x + b)

b = torch.tensor([[10.],
                  [20.]])

print(x + b)

tensor([[11., 22., 33.],
        [14., 25., 36.]])
tensor([[11., 12., 13.],
        [24., 25., 26.]])


In [28]:
import torch
x = torch.tensor([[1., 2., 3.]])

W = torch.randn(3, 2)
b = torch.randn(2)

output = x @ W + b

print("x:", x.shape)
print("W:", W.shape)
print("b:", b.shape)
print("output:", output.shape)


x: torch.Size([1, 3])
W: torch.Size([3, 2])
b: torch.Size([2])
output: torch.Size([1, 2])


**Linear Transformation:** Input Tensor multiplied with matrix of weights and then added with bias vector

z = Wx + b

In [29]:
import torch
layer = torch.nn.Linear(in_features=3, out_features=2)
print(layer.weight.shape)
print(layer.bias.shape)
x = torch.randn(4,3)
y = layer(x)
print(y)
print(y.shape)

torch.Size([2, 3])
torch.Size([2])
tensor([[ 0.2149,  0.0712],
        [ 0.3870, -0.1266],
        [ 0.6557,  0.0019],
        [ 0.4152,  0.7628]], grad_fn=<AddmmBackward0>)
torch.Size([4, 2])


PyTorch stores the weight matrix with shape (out_features, in_features). For an input with shape (batch_size, in_features), the linear transformation is effectively X @ W.T + b.

**Why neural networks need this**

Linear transformations are the basic operations used to transform input features before nonlinear activation functions such as ReLU.

Tensors are the primary data structure used to represent inputs and parameters in neural networks.

Biases are added to the output of the linear transformation and broadcasting allows one bias vector to be added across a batch.

**What I still dont understand**

How exactly are weights and biases determined/learned?

What is the purpose of a linear transformation in a neural network?

In what situations are squeeze() and unsqueeze() useful?

How are in_features and out_features chosen when designing an nn.Linear layer?